Issue #206 -ec2 check to support IMDSv1 and IMDSv2 + moving env vars to conf file
nginxinc/nginx-s3-gateway pull request #212
Opened 2024-02-12 13:36 UTC by orensharoni

we added support of IMDSv2 to the EC2 check with a fall back to IMDSv1,
also, some nginx env declarations were moved from the environment file to the nginx.conf file

2024-02-13 01:40 UTC, 4141done commented
Thank you for your contribution, @orensharoni  - have been able to verify that this fixes your issue from https://github.com/nginxinc/nginx-s3-gateway/issues/206 ?

I'll stand up an ec2 env and give it a check too.

2024-02-14 00:17 UTC, 4141done commented
> yes, I used it on my dev setup and the ec2 test and deployment work, the access_key and access_token should be also verified if posible

Excellent, thank you for confirming.  I'll do a quick check on my end and then merge

2024-02-14 18:59 UTC, 4141done requested changes
Thanks again for your contribution.  I tested these changes with the token approach and was able to verify it works well.

If you can correct the two typoes I highlighted we can go ahead and merge.

2024-02-14 18:59 UTC, 4141done commented on standalone_ubuntu_oss_install.sh
> +  cat >> "/etc/nginx/nginix.conf" << EOF
```suggestion
  cat >> "/etc/nginx/nginx.conf" << EOF
```

2024-02-14 18:59 UTC, 4141done commented on standalone_ubuntu_oss_install.sh
> +    cat >> "/etc/nginx/nginix.conf" << EOF
```suggestion
    cat >> "/etc/nginx/nginx.conf" << EOF
```

2024-02-15 13:52 UTC, orensharoni commented on standalone_ubuntu_oss_install.sh
> +  cat >> "/etc/nginx/nginix.conf" << EOF
done

2024-02-15 13:52 UTC, orensharoni commented on standalone_ubuntu_oss_install.sh
> +    cat >> "/etc/nginx/nginix.conf" << EOF
done

2024-02-15 22:44 UTC, 4141done approved these changes
Thank you again for your contribution! Also special thanks to @HighOnMikey
for noticing the wrong file path in the env var inclusion portion

2024-02-16 02:03 UTC, merged