ci: address OSS scorecard warnings
nginxinc/nginx-s3-gateway pull request #243
Opened 2024-05-06 17:06 UTC by alessfg

### Proposed changes

This PR aims to:
* Remediate the `Token-Permissions` warning/low score by moving the F5 CLA GH Action permissions around.
* Remediate the `Pinned-Dependencies` warning/low score by using specific Docker image SHAs and adding Docker image updates to Dependabot.
* Hopefully remediate the `Vulnerabilities` warning/low score by recreating `package-lock.json`.

### Checklist

Before creating a PR, run through this checklist and mark each as complete:

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md).
- [ ] I have signed the [F5 Contributor License Agreement (CLA)](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md).
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works.
- [ ] If applicable, I have checked that any relevant tests pass after adding my changes.
- [ ] I have updated any relevant documentation (e.g. [`README.md`](/README.md)).

2024-05-06 17:40 UTC, alessfg commented
recheck

2024-05-06 17:48 UTC, alessfg commented
I have hereby read the F5 CLA and agree to its terms

2024-05-06 17:48 UTC, alessfg commented
recheck

2024-05-06 19:59 UTC, 4141done requested changes
A few things here will break our builds but the other stuff looks good!

2024-05-06 22:31 UTC, alessfg commented on Dockerfile.latest-njs
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4
Fixed in the latest commit :)

2024-05-06 22:31 UTC, alessfg commented on Dockerfile.unprivileged
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4
Fixed in the latest commit :)

2024-05-06 22:32 UTC, alessfg commented on examples/brotli-compression/Dockerfile.oss
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4@sha256:8aa48324479b3653b
The three examples here already pull the image from Docker Hub so including the latest available SHA should be ok?

2024-05-06 22:32 UTC, alessfg commented on examples/gzip-compression/Dockerfile.oss
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4
See previous comment

2024-05-06 22:32 UTC, alessfg commented on examples/modsecurity/Dockerfile.oss
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4
See previous comment

2024-05-07 18:53 UTC, merged

2024-05-07 19:09 UTC, alessfg commented on examples/gzip-compression/Dockerfile.oss
> +FROM nginxinc/nginx-s3-gateway@sha256:8aa48324479b3653b5936183cc97f2ca1aa9078d229042f1bca357834bd906f4
Dependabot should hopefully take care of Docker SHA updates! 😁